# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [3]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [4]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [5]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [6]:
data.shape

(506, 14)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [8]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [9]:
# Your code here :
X = data.drop('MEDV', axis=1)
y = data['MEDV']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
477,15.02340,0.0,18.10,0,0.6140,5.304,97.3,2.1007,24,666.0,20.2,349.48,24.91
15,0.62739,0.0,8.14,0,0.5380,5.834,56.5,4.4986,4,307.0,21.0,395.62,8.47
332,0.03466,35.0,6.06,0,0.4379,6.031,23.3,6.6407,1,304.0,16.9,362.25,7.83
423,7.05042,0.0,18.10,0,0.6140,6.103,85.1,2.0218,24,666.0,20.2,2.52,23.29
19,0.72580,0.0,8.14,0,0.5380,5.727,69.5,3.7965,4,307.0,21.0,390.95,11.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.17120,0.0,8.56,0,0.5200,5.836,91.9,2.2110,5,384.0,20.9,395.67,18.66
270,0.29916,20.0,6.96,0,0.4640,5.856,42.1,4.4290,3,223.0,18.6,388.65,13.00
348,0.01501,80.0,2.01,0,0.4350,6.635,29.7,8.3440,4,280.0,17.0,390.94,5.99
435,11.16040,0.0,18.10,0,0.7400,6.629,94.6,2.1247,24,666.0,20.2,109.85,23.27
102,0.22876,0.0,8.56,0,0.5200,6.405,85.4,2.7147,5,384.0,20.9,70.80,10.63

In [11]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
173,0.09178,0.0,4.05,0,0.510,6.416,84.1,2.6463,5,296.0,16.6,395.50,9.04
274,0.05644,40.0,6.41,1,0.447,6.758,32.9,4.0776,4,254.0,17.6,396.90,3.53
491,0.10574,0.0,27.74,0,0.609,5.983,98.8,1.8681,4,711.0,20.1,390.11,18.07
72,0.09164,0.0,10.81,0,0.413,6.065,7.8,5.2873,4,305.0,19.2,390.91,5.52
452,5.09017,0.0,18.10,0,0.713,6.297,91.8,2.3682,24,666.0,20.2,385.09,17.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,18.81100,0.0,18.10,0,0.597,4.628,100.0,1.5539,24,666.0,20.2,28.79,34.37
436,14.42080,0.0,18.10,0,0.740,6.461,93.3,2.0026,24,666.0,20.2,27.49,18.05
411,14.05070,0.0,18.10,0,0.597,6.657,100.0,1.5275,24,666.0,20.2,35.05,21.22
86,0.05188,0.0,4.49,0,0.449,6.015,45.1,4.4272,3,247.0,18.5,395.99,12.86
75,0.09512,0.0,12.83,0,0.437,6.286,45.0,4.5026,5,398.0,18.7,383.23,8.94

In [13]:
X_train.shape

(404, 13)

In [14]:

X_test.shape

(102, 13)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [15]:
# Your code here :
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [16]:
model.fit(X_train, y_train)

LinearRegression()

In [17]:
y_train_pred = model.predict(X_train)
y_train_pred

array([10.96952405, 19.41196567, 23.06419602, 12.1470648 , 18.3738116 ,
       25.24677946, 20.77024774, 23.90932632,  7.81713319, 19.60988098,
       21.8202963 , 27.59615864, 32.67986504, 15.12308446, 35.3964561 ,
       12.99688651, 20.728181  , 28.30223542, 15.61724836, 24.45143096,
        4.61794591, 23.76681932, 25.56178249, 22.98928526, 24.5213025 ,
       34.06407919, 19.71166707, 39.11233072, 14.62515846, 24.81139885,
       18.02332883, 20.85836445,  9.57577261, 20.87246835, 22.28583096,
       31.79327155, 31.04748307, 15.70611763, 17.01382935, 28.23332703,
       24.27661276, 16.88670215,  6.90720745, 26.75808901, 22.586493  ,
       17.53664716, 13.77197016, 41.04840929, 16.44690754, 18.23531669,
       25.37038646, 23.64581399, 22.05322581, 20.83620499, 16.93508273,
       22.797579  , 29.13333934,  7.69310515, 24.60571452, 17.2358028 ,
       21.10846551, 25.15150324, 27.33394823, 21.30494963, 41.5811902 ,
       19.19666651, 15.37955448, 19.33545877, 17.04687638, 22.96801532,
       23.11094953, 33.6977586 , 22.77436405, 20.28968381, 25.35517813,
       31.02479125, 33.05103792, 28.44712333,  8.50926331,  5.61220643,
       12.81228164, 19.81854491, 34.8603548 , 33.47481463, 15.81288676,
        4.16863764, 32.81131556, 21.22307142, 18.97752706, 26.36174269,
       18.38053781, 17.80316891, 11.8730344 , 31.84801205, 24.45344478,
       20.0222241 , 19.5225374 , 11.8723419 , 28.90289906, 19.7133604 ,
       32.47093634, 33.20696505, 24.79405395, 21.25197228, 25.03045081,
       43.36995367, 29.54151469, 33.75302939, 26.27516427, 27.04791799,
       15.1908027 , 31.34177077, 20.85218327, 31.05070715, 28.74449991,
       21.16535503, 23.06717742, 12.48881717, 36.48751917, 37.24291141,
       33.23617345,  5.30863493, 20.82773333, 22.16769067, 35.62579793,
       17.10890633, 22.76667   , 19.50567599, 26.36980524, 16.03780391,
       20.63186041, 27.04508116, 31.39596353, 31.12597743, 22.78355908,
       39.11521781, 28.28378993, 30.53090392, 28.89518723, 21.08389783,
       29.04801464, 16.151087  , 22.08243372, 24.61505524, 18.95878457,
        2.06366066, 20.51120467, 26.85927261, 23.0775764 , 18.40141847,
       22.70378324, 15.95162657, 31.54559763, 27.82356386, 34.19210038,
       20.70876151, 15.1538496 , 19.55740929,  8.31853813, 13.62525632,
       26.48611752, 16.52769982,  4.13593772, 24.73356662, 12.21856959,
       28.24704463, 33.60549853, 36.84177072, 24.28136146, 20.7199677 ,
       30.79885576, 36.93823489, 19.92152434, 19.59433404, 28.76197718,
       13.28347615, 13.41116334, 10.89910148, 19.07573086, 22.65911351,
       30.27080271, 29.77482371, 17.89252221, 29.83838757, 14.41987694,
       13.24056207, 33.87859379, 19.6406762 , 14.54072369, 23.66498192,
       22.41851151, 19.63248447, 24.660086  , 35.00833944,  4.12171868,
       20.79593953, 33.240402  , 18.04778742, 22.6208596 , 22.39592759,
       21.4012853 , 11.74782838, 38.18786922, 25.76751814, 24.80115706,
       16.36524419, 31.98045427, 36.35420843, 39.11016375, 20.33864814,
       22.16464728, 16.34276966, 39.35137104,  6.74954317, 21.35789894,
       15.53370378, 26.91527204,  8.80382559, 20.93301971, -0.20588155,
       17.21501492, 16.17150935,  8.48374754, 23.08202496, 17.23085262,
       29.42673011, 44.36436789, 28.09470335, 23.75911874, 36.75959172,
        8.71594791, 25.90885934, 20.83832124, 23.68119542, 19.85753143,
       22.2992237 , 14.72942336, 18.4266911 , 22.45346464, 23.75648384,
       28.82492146, 23.58310886, 27.30142666, 18.06532614, 13.16799771,
       31.66795775, 28.77291955, 12.60179253, 17.38668341, 24.05174693,
       40.7163898 , 23.0214736 , 12.83596226, 28.55024128, 36.850343  ,
       23.26391794, 25.14113573, 38.36624745, 18.21318365, 25.69614391,
       15.22833068, 24.14345412, 36.27095489, 31.03140871, 24.82017075,
       17.7834844 , 17.99307546,  8.61827851, 41.51965821, 19.63259696,
       30.16241039, 19.69581658, 14.59963591, 20.29467675, 24.22053288,
       34.79282666, 26.51552807, 41.665796  , 12.32829593, 14.32092274,
       23.69090327, 18.01762114, 19.72399411, 29.13009315, 11.10216617,
       24.11213143, 18.54668994, 23.69765843, 30.11853879, 19.34756033,
       12.52355093, 33.74737806, 16.90295464, 17.83165159, 19.34064029,
       26.74379491, 35.24575625, 12.92253178, 26.69073573, 19.19640769,
       30.29549933, 17.83878909, 22.92058129, 29.13254708, 20.02093559,
       25.18893157, 20.95650827, 20.57624549, 32.93168351, 20.43565472,
       25.41798459, 28.14952635, 37.59066882, 25.0548289 , 28.61534646,
       17.97695227, 30.78085325, 23.57491321, 34.56676284, 18.52592551,
       23.86972656, 13.82862001, 25.18152388, 17.67219765, 12.63704156,
       17.03927502, 14.2510159 , 28.56862619, 22.99037971, 13.42262376,
       17.40965124, 34.44268371, 12.93938984, 14.62427657, 27.50209814,
       21.28772373, 21.8475453 , 27.75030943, 16.84106111, 35.70395065,
       23.19717187, 19.70894368, 20.39856551, 31.03155183,  5.16165827,
       36.26386827, 38.27409562, 21.44507004, 21.53203698, 13.25546637,
       35.43733953, 19.75468373, 21.59325014, 27.28654912, 14.70336355,
       20.10948908, 20.98738625, 20.42268561, 26.20840113, 11.28815662,
       34.57059129, 22.65270668, 22.68814063, 33.20155069, 26.77878535,
       21.55230365,  8.80963918, 28.40878163, 25.10012639, 25.47646583,
       17.70215249, 25.63601841, 18.61140436, 32.77937269, 35.77461311,
       18.3180684 , 30.14080347,  7.72488159, 26.25987699, 10.52826879,
       27.30604251, 44.10078731, 28.92351314, 14.7836951 , 20.79445301,
       17.96782515, 19.333174  , 33.02714571, 25.71055958, 25.89232968,
       17.07165041, 21.95432205, 11.3511532 , 13.27742402, 22.66485295,
       22.52252947, 12.30424735, 32.08396429, 22.11175771, 17.24071878,
       22.00480027, 26.7237425 , 12.97674212, 19.14279551])

In [18]:

y_test_pred = model.predict(X_test)

y_test_pred

array([28.99672362, 36.02556534, 14.81694405, 25.03197915, 18.76987992,
       23.25442929, 17.66253818, 14.34119   , 23.01320703, 20.63245597,
       24.90850512, 18.63883645, -6.08842184, 21.75834668, 19.23922576,
       26.19319733, 20.64773313,  5.79472718, 40.50033966, 17.61289074,
       27.24909479, 30.06625441, 11.34179277, 24.16077616, 17.86058499,
       15.83609765, 22.78148106, 14.57704449, 22.43626052, 19.19631835,
       22.43383455, 25.21979081, 25.93909562, 17.70162434, 16.76911711,
       16.95125411, 31.23340153, 20.13246729, 23.76579011, 24.6322925 ,
       13.94204955, 32.25576301, 42.67251161, 17.32745046, 27.27618614,
       16.99310991, 14.07009109, 25.90341861, 20.29485982, 29.95339638,
       21.28860173, 34.34451856, 16.04739105, 26.22562412, 39.53939798,
       22.57950697, 18.84531367, 32.72531661, 25.0673037 , 12.88628956,
       22.68221908, 30.48287757, 31.52626806, 15.90148607, 20.22094826,
       16.71089812, 20.52384893, 25.96356264, 30.61607978, 11.59783023,
       20.51232627, 27.48111878, 11.01962332, 15.68096344, 23.79316251,
        6.19929359, 21.6039073 , 41.41377225, 18.76548695,  8.87931901,
       20.83076916, 13.25620627, 20.73963699,  9.36482222, 23.22444271,
       31.9155003 , 19.10228271, 25.51579303, 29.04256769, 20.14358566,
       25.5859787 ,  5.70159447, 20.09474756, 14.95069156, 12.50395648,
       20.72635294, 24.73957161, -0.164237  , 13.68486682, 16.18359697,
       22.27621999, 24.47902364])

## 3. Calculate and print R-squared for both the training and the testing set.

In [19]:
# Your code here :

from sklearn.metrics import r2_score
r2_train = r2_score(y_train, y_train_pred)

r2_train

0.7508856358979672

In [20]:
r2_test = r2_score(y_test, y_test_pred)
r2_test

0.6687594935356318

## 4. Calculate and print mean squared error for both the training and the testing set.

In [21]:
# Your code here :
from sklearn.metrics import mean_squared_error

mse_train = mean_squared_error(y_train, y_train_pred)

mse_train

21.641412753226316

In [22]:
mse_test = mean_squared_error(y_test, y_test_pred)
mse_test

24.291119474973534

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [23]:
# Your code here :
from sklearn.metrics import mean_absolute_error
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_train

3.314771626783226

In [24]:
mae_test = mean_absolute_error(y_test, y_test_pred)
mae_test

3.189091965887842

## Classification Model Evaluation

In [25]:
from sklearn.datasets import load_iris
data = load_iris()

In [26]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [28]:
column_names = data.feature_names
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
df = pd.DataFrame(data['data'],columns=column_names)

In [34]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [35]:
target = pd.DataFrame(data.target)

In [36]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [43]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [46]:
# Your code here :
from sklearn.model_selection import train_test_split


X = data.data      
y = data.target

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)

In [48]:
X_train

array([[4.4, 2.9, 1.4, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [6.8, 2.8, 4.8, 1.4],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 2.5, 4. , 1.3],
       [6.3, 2.5, 5. , 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [6.3, 2.8, 5.1, 1.5],
       [7.7, 3. , 6.1, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [5. , 2. , 3.5, 1. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.8, 2.6, 4. , 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3.4, 1.5, 0.4],
       [6.3, 2.5, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3. , 1.6, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.4, 1.6, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.7, 1.5, 0.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 5.4, 2.1],
       [6.2, 3.4, 5.4, 2.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.9, 3.2, 4.8, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [7. , 3.2, 4.7, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [7.4, 2.8, 6.1, 1.9],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 2.7, 5.1, 1.9],
       [5. , 3.2, 1.2, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [5.6, 2.9, 3.6, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.4, 5.6, 2.4],
       [4.6, 3.2, 1.4, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 3.5, 1.3, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.7, 2.5, 5. , 2. ],
       [4.8, 3.4, 1.9, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [5.5, 2.6, 4.4, 1.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 3.2, 5.3, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.6, 1.4, 0.2],
       [6. , 2.2, 5. , 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [7.2, 3. , 5.8, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.7, 4.9, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [4.9, 3.1, 1.5, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [6.2, 2.2, 4.5, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [6.9, 3.2, 5.7, 2.3],
       [5.2, 4.1, 1.5, 0.1],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 4.7, 1.5],
       [4.8, 3.1, 1.6, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.8, 1.9, 0.4],
       [4.3, 3. , 1.1, 0.1],
       [6.7, 3.3, 5.7, 2.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.8, 3. , 5.5, 2.1],
       [6.3, 2.3, 4.4, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.4, 3.9, 1.7, 0.4],
       [6.8, 3.2, 5.9, 2.3],
       [5.7, 2.9, 4.2, 1.3],
       [7.2, 3.2, 6. , 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.3, 3.7, 1.5, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.7, 3. , 4.2, 1.2],
       [5.6, 3. , 4.1, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 3.5, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [6. , 2.2, 4. , 1. ],
       [5.9, 3. , 4.2, 1.5],
       [4.8, 3.4, 1.6, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2]])

In [49]:
X_test

array([[4.4, 3. , 1.3, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [4.6, 3.6, 1. , 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3. , 4.5, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [6.4, 3.2, 4.5, 1.5],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [6.1, 2.9, 4.7, 1.4],
       [6. , 3. , 4.8, 1.8],
       [5.4, 3.7, 1.5, 0.2],
       [6.7, 3.1, 5.6, 2.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.8, 5.6, 2.2],
       [6.7, 3. , 5. , 1.7],
       [6.6, 3. , 4.4, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6.5, 3. , 5.5, 1.8],
       [5.2, 3.4, 1.4, 0.2]])

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [50]:
# Your code here :
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [51]:
model.fit(X_train, y_train)

LogisticRegression()

In [52]:
y_train_pred = model.predict(X_train)
y_train_pred

array([0, 1, 1, 0, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 2, 2, 0, 1, 0,
       2, 0, 1, 2, 2, 0, 2, 0, 0, 1, 1, 0, 2, 2, 1, 1, 2, 2, 0, 1, 0, 2,
       0, 0, 2, 0, 0, 0, 0, 1, 2, 1, 0, 2, 1, 2, 0, 2, 0, 1, 2, 0, 2, 1,
       2, 1, 1, 2, 0, 0, 0, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 0, 2, 0, 2, 1,
       1, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1,
       0, 2, 1, 1, 0, 0, 0, 0, 1, 0])

In [53]:
y_test_pred = model.predict(X_test)
y_test_pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 2, 1, 0, 2, 0])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [54]:
# Your code here :
from sklearn.metrics import accuracy_score
print("Training Accuracy:", accuracy_score(y_train, y_train_pred))

Training Accuracy: 0.975

In [55]:
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred))

Testing Accuracy: 0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [56]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score
train_bal_acc = balanced_accuracy_score(y_train, y_train_pred)
train_bal_acc

0.975

In [57]:
test_bal_acc = balanced_accuracy_score(y_test, y_test_pred)
test_bal_acc

0.9666666666666667

## 10. Calculate and print the precision score for both the training and the testing set.

In [58]:
# Your code here :
from sklearn.metrics import precision_score


train_precision = precision_score(
    y_train,
    y_train_pred,
    average='weighted'
)

train_precision

0.9751928288513655

In [59]:
test_precision = precision_score(
    y_test,
    y_test_pred,
    average='weighted'
)

test_precision

0.9696969696969696

## 11. Calculate and print the recall score for both the training and the testing set.

In [60]:
# Your code here :
from sklearn.metrics import recall_score


train_recall = recall_score(
    y_train,
    y_train_pred,
    average='weighted'
)
train_recall

0.975

In [61]:
test_recall = recall_score(
    y_test,
    y_test_pred,
    average='weighted'
)

test_recall

0.9666666666666667

## 12. Calculate and print the F1 score for both the training and the testing set.

In [62]:
# Your code here :
from sklearn.metrics import f1_score

# Calculate F1 Score
train_f1 = f1_score(
    y_train,
    y_train_pred,
    average='weighted'
)

train_f1

0.9749960931395532

In [63]:
test_f1 = f1_score(
    y_test,
    y_test_pred,
    average='weighted'
)

test_f1

0.9665831244778613

## 13. Generate confusion matrices for both the training and the testing set.

In [64]:
# Your code here :

from sklearn.metrics import confusion_matrix

# Training confusion matrix
cm_train = confusion_matrix(y_train, y_train_pred)

cm_train

array([[40,  0,  0],
       [ 0, 38,  2],
       [ 0,  1, 39]], dtype=int64)

In [65]:
cm_test = confusion_matrix(y_test, y_test_pred)
cm_test

array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 10]], dtype=int64)

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !